name: "Update LineageOS"

on: { schedule: [{ cron: '0 0 * * 0' }], workflow_dispatch }

jobs:
  updates:
    name: "Update LineageOS"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.5
    - uses: cachix/install-nix-action@v31.1.0
      with:
        extra_nix_config: "experimental-features = nix-command flakes"
    - name: "Set OLD_BUILD_NUMBER variable"
      run: echo "OLD_BUILD_NUMBER=$(nix eval -f . --arg configuration "{flavor = \"lineageos\";}" --raw config.buildNumber)" >> $GITHUB_ENV
    # - name: "Fetch latest lineage-18.1 changes"
    #   run: nix develop -c ./flavors/lineageos/update.sh lineage-18.1
    # - name: "Fetch latest lineage-17.1 changes"
    #   run: nix develop -c ./flavors/lineageos/update.sh lineage-17.1
    - name: "Update buildDateTime"
      run: date +%s > flavors/lineageos/lineage-22.1/lastUpdated.epoch
    - name: "Set NEW_BUILD_DATE_TIME variable"
      run: echo "NEW_BUILD_NUMBER=$(nix eval -f . --arg configuration '{ flavor = "lineageos"; device = "foo"; androidVersion = 15; }' --raw config.buildNumber)" >> $GITHUB_ENV
    - name: "Create Pull Request"
      id: cpr
      uses: peter-evans/create-pull-request@v3.10.1
      with:
        commit-message: "lineageos: ${{ env.OLD_BUILD_NUMBER }} -> ${{ env.NEW_BUILD_NUMBER }}"
        title: "lineageos: ${{ env.OLD_BUILD_NUMBER }} -> ${{ env.NEW_BUILD_NUMBER }}"
        branch: "lineageos-${{ env.NEW_BUILD_NUMBER }}"
        delete-branch : true
        labels: "automated"
    - name: "Check outputs"
      run: |
        echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
        echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
